[package]
name = "ensight"
version = "0.1.0"
authors = ["yasuyuky <yasuyuki.ymd@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = "1.0.145"
serde_json = "1.0.87"
surf = "2.0.0"
colored = "2.0.0"
toml = "0.5.9"
once_cell = "1.15.0"
colorgrad = "0.6.2"
either = { version = "1.8.0", features = ["serde"] }
serde_yaml = "0.9.14"
anyhow = "1.0.66"
base64 = "0.13.0"
time = { version = "0.3.15", features = ["serde", "serde-well-known"] }
clap = { version = "4.0.18", features = ["derive"] }

[dependencies.async-std]
features = ["attributes"]
version = "1.12.0"
