[package]
name = "ensight"
version = "0.1.0"
authors = ["yasuyuky <yasuyuki.ymd@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = "1.0.193"
serde_json = "1.0.109"
surf = "2.0.0"
colored = "2.1.0"
once_cell = "1.19.0"
colorgrad = "0.6.2"
anyhow = "1.0.77"
base64 = "0.21.5"
time = { version = "0.3.31", features = ["serde", "serde-well-known"] }
clap = { version = "4.4.12", features = ["derive"] }

[dependencies.async-std]
features = ["attributes"]
version = "1.12.0"
